apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: weather
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: EMAIL_HERE
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}